Feature/list command
CommCody/adr-cli pull request #4
Opened 2020-10-08 12:32 UTC by Defkon1

**Major changes:**

- Added -l|--list command

**Minor changes:**
- updated README

Requires classes from #3

2020-10-11 14:19 UTC, CommCody requested changes
These changes will only work after #3 is adapted

2020-10-11 14:19 UTC, CommCody commented on src/adr/Program.cs
> +                    var records = manager.GetList();
```suggestion
                    var records = log.GetRecords();
```

2020-10-11 14:19 UTC, CommCody commented on src/adr/Program.cs
> +                    AdrManager manager = new AdrManager(System.IO.Path.GetFullPath(docFolder));
```suggestion
                    var log = new ArchitectureDecisionLog(System.IO.Path.GetFullPath(docFolder));
```

2020-10-13 18:39 UTC, CommCody approved these changes
I'm sorry, but some time was available and I wanted to try to help you finish some of this work.
To integrate this work with the one we finished in #3 I rebased this branch on main, so you might have to reset your local branch

Let me know if you think this is done, or you want to add some more ?

2020-10-14 06:25 UTC, Defkon1 commented
I solved conflicts on my branch and renamed the ex-AdrManager class to reflect the new class name

2020-10-17 11:41 UTC, merged